pub(crate) mod applet_frame;
pub(crate) mod button;
pub(crate) mod header;
pub(crate) mod image;
pub(crate) mod label;
pub(crate) mod rectangle;
pub(crate) mod scrolling_frame;
pub(crate) mod sidebar;
pub(crate) mod tab_frame;